spring:
  dataSource:
    password: games
    username: games
    url: jdbc:mysql://10.4.50.100:49154/games-with-friends

logging:
  level:
    root: warn
    '[com.promineo]': debug
    
#server:
#port: 8081